<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Bcl.Memory" Version="$(MicrosoftBclMemoryVersion)" />
		<PackageReference Include="Microsoft.ML" Version="$(MicrosoftMlVersion)" />
		<PackageReference Include="Microsoft.ML.TorchSharp" Version="$(MicrosoftMlTorchSharpVersion)" />
		<!-- We use the GPU based package for training a model or generating training data -->
		<!--<PackageReference Include="TorchSharp-cuda-windows" Version="$(TorchSharpCpuVersion)" />-->
		<!-- We use the CPU based package for deployment -->
		<!-- We use the CPU based package for production -->
		<PackageReference Include="TorchSharp-cpu" Version="$(TorchSharpCpuVersion)" />
		<PackageReference Include="Serilog.AspNetCore" Version="$(SerilogAspNetCoreVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GammonX.Engine\GammonX.Engine.csproj" />
		<ProjectReference Include="..\GammonX.Models\GammonX.Models.csproj" />
	</ItemGroup>

</Project>
